#! /bin/zsh

for i in ~/Music/**/*.mp3; do
    declare input=$i output=${i/Music/MP3}
    dirname="$(dirname ${output})"

    mkdir -p "${dirname}"
    cp -uv "${input}" "${dirname}"
done

for i in ~/Music/**/*.flac; do
    echo ${i}
    declare input=$i output=${i/Music/MP3}
    output=${output/flac/mp3}

    mkdir -p "$(dirname ${output})"
    if $(which ffmpeg >> /dev/null); then
        ffmpeg -loglevel quiet -i "${input}" -c:a libmp3lame -b:a 192k -n "${output}"
    elif $(which avconv >> /dev/null); then
        avconv -loglevel quiet -i "${input}" -c:a libmp3lame -b:a 192k -n "${output}"
    fi
    sync
done
