#! /bin/zsh

for i in ~/Music/**/*.mp3; do
    declare input=$i output=${i/Music/MP3}
    dirname="$(dirname ${output})"

    mkdir -p "${dirname}"
    cp -uv "${input}" "${dirname}"
done

for i in ~/Music/**/*.flac; do
    declare input=$i output=${i/Music/Opus}
    output=${output/flac/opus}
    output=${output/mp3/opus}

    mkdir -p "$(dirname ${output})"
    ffmpeg -i "$input" -c:a libopus -b:a 128k -n "${output}"
    sync
done
