#!/usr/bin/env bash
set -e

if [[ $# -lt 2 || ! $1 =~ ^[0-9]+$ ]]; then
    >&2 echo "USAGE: git bcs <number> <description>"
    exit 1
fi

DESCRIPTION="$@"
BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "${BRANCH}" =~ ^(FEATURES-[0-9]{3,})- ]]; then
    FEATURE="${BASH_REMATCH[1]}"
else
    >&2 echo "Be sure to be on a feature branch"
    exit 2
fi

git checkout -b ${FEATURE}-${DESCRIPTION// /-}
