#!/bin/sh
PATH=/bin:/usr/bin
DIR=${1:-~/Maildir}

for d in "${DIR}"/*; do
    [ "${d}" = "${DIR}/INBOX" ]              && continue
    [ "${d}" = "${DIR}/INBOX.Archives" ]     && continue
    [ "${d}" = "${DIR}/INBOX.Drafts" ]       && continue
    [ "${d}" = "${DIR}/INBOX.Junk" ]         && continue
    [ "${d}" = "${DIR}/INBOX.Sent" ]         && continue
    [ "${d}" = "${DIR}/INBOX.Templates" ]    && continue
    [ "${d}" = "${DIR}/INBOX.Trash" ]        && continue
    [ $(find "${d}" -type f | wc -l) -eq 0 ] && rmdir -v "${d}"/cur "${d}"/new "${d}"/tmp "${d}"
done

exit 0
# vim: filetype=sh textwidth=80
