#!/bin/sh
PATH=/bin:/usr/bin
DIR=${1:-~/Maildir}

for d in "${DIR}"/*; do
    [ "${d}" = "${DIR}/INBOX" ]                 && continue
    [ "${d}" = "${DIR}/INBOX.drafts" ]          && continue
    [ "${d}" = "${DIR}/INBOX.junk" ]            && continue
    [ "${d}" = "${DIR}/INBOX.sent" ]            && continue
    [ "${d}" = "${DIR}/INBOX.templates" ]       && continue
    [ "${d}" = "${DIR}/INBOX.trash" ]           && continue
    [ $(find "${d}" -type f | wc -l) -eq 0 ]    && \
        rmdir -v "${d}"/cur "${d}"/new "${d}"/tmp "${d}"
done

# vim: filetype=sh textwidth=80
